### ISSUE TITLE
GL_EXTENSIONS might have the wrong value

### ISSUE THREAD

**Issue by phaazon** [ekmett/gl#11]
My program segfault and I try extract the supported extensions. I’m using the following code:

```haskell
getGLExtensions :: (MonadIO m) => m [String]
getGLExtensions = liftIO . fmap (splitOn ",") $ glGetString GL_EXTENSIONS >>= peekCString . castPtr
```

**Comment by ekmett** [comment]
Use http://hackage.haskell.org/package/gl-0.7.7/docs/src/Graphics-GL-Internal-Proc.html#extensions

**Comment by ekmett** [comment]
`glGetString GL_EXTENSIONS` generally can't be counted upon to work, hence the existence of that definition. This isn't the fault of the binding so much as that being a legacy approach that just doesn't work on anything recent.

**Comment by phaazon** [comment]
Hm, I wonder why. Anyways, thanks!

**Comment by ekmett** [comment]
The short version of it is vendors started with assumptions of string length limits, and the number of extensions quickly overwhelmed those assumptions! Hence the switch from `glGetString` to get all of them to `glGetStringi` to get each in turn after getting a count as of OpenGL 3. Each individual extension name is short.

The preferred way, if you don't need to print them all or something, to access them in gl is to use the booleans in each module for each extension as it will memoize the lookup.

e.g.

`gl_IMG_multisampled_render_to_texture` in [`Graphics.GL.Ext.IMG.MultisampledRenderToTexture`](http://hackage.haskell.org/package/gl-0.7.7/docs/Graphics-GL-Ext-IMG-MultisampledRenderToTexture.html)

**Comment by phaazon** [comment]
Thanks! Crystal clear now!
