### ISSUE TITLE
Release 0.8.0 to cabal

### ISSUE THREAD

**Issue by lukexi** [ekmett/gl#15]
As noted — it's missing from Stackage currently (due to the directory 1.3 thing that's now fixed in HEAD)

**Comment by ekmett** [comment]
Sounds good. I'll run a local build test and then push it out.

**Comment by ekmett** [comment]
It looks like I should fix up the Setup dependencies to handle modern cabal while I'm at it. I'm willing to cut off old GHC/cabal combinations given the older versions are out there, and it causes me linking problems on OSX to actually setup at present.

**Comment by ekmett** [comment]
Done.
