### ISSUE TITLE
EGL Support

### ISSUE THREAD

**Issue by TravisWhitaker** [ekmett/gl#18]
I think the infrastructure used to generate this library could be straightforwardly extended to provide EGL bindings as well. Would there be interest in doing so? There might be good arguments for having EGL live in a separate package; I'm not sure if it's always available on Windows or macOS, for example. Barring those, I think it'd be great to have that API available in this package too.

**Comment by ekmett** [comment]
Up until now all of the window management stuff that is platform specific we've considered out of scope for this package. It varies too much platform by platform. EGL, WGL, CGL, GLX, AIGLX, even stuff like sdl2, GLUT, etc. all provide ways to get buffers, write to windows, etc.

Adding direct support for any one of them means picking up a library dependency that rather complicates building the project, and none of them necessarily have direct analogues on all of the platforms we can build on. I strongly suspect we'd want to stick to the status quo and have those be provided by external libraries. 

With that model in mind, while I have no objection to a separate `egl` package existing, and it'd be great to have, I have no particular expertise to bring to the table to help bring it about.

**Comment by schell** [comment]
I think it's possible to have the cake and eat it too, if the infrastructure you're referring to @TravisWhitaker could be extracted into a separate lib that `gl` consumes to generate its bindings. If that's within a reasonable amount of work (reasonable as in - someone is willing to do it), then an `egl` package could also consume said library to use in generating its bindings. In that case `egl` could include any extra deps at no cost to `gl`. The question then @TravisWhitaker is are you willing to part out and maintain the infrastructure and @ekmett is that an acceptable solution?

**Comment by ekmett** [comment]
@schell I don't understand your proposed solution, as I don't see what the `gl` package needs to "generate" to use a separate `egl` package. 

The only possible exception that comes to mind is trying to call out to `eglGetProcAddress` rather than `glXGetProcAddressARB`. That _should_ just work almost if not exactly "as is" with no modification like it does with other third-party platform backends, possibly with an extra line or two in [cbits/gl.c](https://github.com/ekmett/gl/blob/087ae76122f8c72f567cdfe3889052bf713c576e/cbits/gl.c#L88) adding `eglGetProcAddress` as a possible dynamic linking target, and maybe an optional compilation flag like the one we have for `useglxgetprocaddress` to bypass dynamic linking entirely and ensure that you link against it directly. It'd probably need a little more love if you want to run EGL on windows. I don't know enough about EGL on Windows or the build issues you'd face off hand to comment in detail on that usecase, though.

**Comment by ekmett** [comment]
If somebody wanted to build a separate `egl` package and throw a patch in here that added `eglGetProcAddress` to the list of things we tried to resolve against / added a separate compilation flag for `egl`, and/or wanted to chase down how to link against it "properly" on windows, so that we could compile in a mode where you could use it there too, I'd happily take patches in that direction, but the bulk of the work would take place outside of the `gl` package.

**Comment by schell** [comment]
@ekmett I was referring to parting out what `gl` uses to generate its bindings. It may be obvious that I don't know what I'm talking about, but I was assuming that `gl` reads the OpenGL XML spec and uses that to generate bindings. If that's correct then I'm also assuming that @TravisWhitaker would like to generate bindings for `egl` in the same manner - by reading a similarly formatted XML spec for EGL. 

If all those assumptions hold then it might be worth it to extract `Module.hs`, `Parser.hs` and friends into a separate library so both `gl` and `egl` can use them for their parsing and generation steps. That may be overkill though, it may be better just to copy, paste and maintain two separate sources. Forgive me if these comments are too noisy.

**Comment by ekmett** [comment]
The lowest impact version would probably would be to copy/paste into a similar `egl` package. We have to do a lot of massaging of the data to fix up bugs in the spec, in ways that are rather peculiar to the `gl` package. At least if we continue to do code generation the way we do today.

That said, I've been meaning to get around to extracting the code generation into a separate package, that way the `gl` package won't need `hxt`, etc. and all those other heavy weight dependencies to build. You'd just need to use the generator package when building the `gl` package from scratch to ship to hackage. When Sven adopted the approach we were using here for `HOpenGL`, he did it this way. There is a lot to be said for that approach, as it speeds compilation of the package considerably in sandboxes. Even if I have to get over checking in built artifacts.

If we pulled the code that generates packages from Khronos style xml specifications out into a separate package that is only used by maintainers, etc. we might be able to get some code reuse across a bunch of packages for `gl`, `egl`, `wgl`, `glx`, `opengl-sc`, `openvx`, `opensl-es`, maybe updating the old `vulkan` bindings that we have for haskell, etc.

The gl/glx/wgl xml specifications all live side by side in [The OpenGL-Registry](https://github.com/KhronosGroup/OpenGL-Registry/tree/master/xml)

The egl specification lives in the [EGL Registry](https://github.com/KhronosGroup/EGL-Registry/blob/master/api/egl.xml)

I'm not sure where the opengl sc xml extension registry lives or if it does at all.

It looks like OpenSL-ES doesn't have a standardish khronos xml specification I can find in the registry
[OpenSL-ES Registry](https://github.com/KhronosGroup/OpenSL-ES-Registry)

but the vulkan spec is in the [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs/blob/master/xml/vk.xml) repository.

I couldn't find the one for OpenVX, etc.

As you can see there is a bit of ad hoc inconsistency to how Khronos packages up and documents all of these different APIs and I've yet to see how similar the xml formats are for each of those, so there is a fair bit of work to be had. I'm happy to house and coordinate it, but it'd need a fair bit of volunteer effort.

It also seems like a lot of Khronos' newer efforts, OpenKODE, OpenMAX AL, etc. lack xml specs.

**Comment by schell** [comment]
Thanks for hashing that out @ekmett. @TravisWhitaker any thoughts?

**Comment by TravisWhitaker** [comment]
@schell What you described above is what I had in mind.  What I thought might distinguish EGL and make it worthy for inclusion in `gl` over other display and context management libraries is the fact that Khronos provides an XML spec, whereas WGL, GLX, etc. aren't so nicely specified.

I do like the idea of breaking out the code generation machinery into a separate package.

**Comment by ekmett** [comment]
They also have xml specifications in the same format.

**Comment by TravisWhitaker** [comment]
Whoa, so they do, I hadn't seen those before. That's extremely useful! I'd be nice to have a little family of these low-level libraries.

**Comment by TravisWhitaker** [comment]
We ended up needing some EGL bindings at work so I was able to take a crack at this. When time permits I'll polish things up and we'll open up the package.
