### ISSUE TITLE
glPathGlyphIndexRangeNV's type is wrong

### ISSUE THREAD

**Issue by svenpanne** [ekmett/gl#6]
For some strange reason (probably an oversight), glPathGlyphIndexRangeNV's last command parameter is described in a slightly unusual way:

            <param><ptype>GLuint</ptype> <name>baseAndCount</name>[2]</param>

Probably this should just be:

            <param><ptype>GLuint</ptype> *<name>baseAndCount</name></param>

gl's type parser is a bit too naive just counting the `*` characters, so it simply emits `GLuint` instead of `Ptr GLuint`. Special-casing this is probably the right way to handle this, as it is the only place in gl.xml, glx.xml, egl.xml and wgl.xml where this happens.

**Comment by ekmett** [comment]
Good catch. We'll patch.

**Comment by ekmett** [comment]
Uploaded as `0.7`.
